version: '3.9'

services:
  spring:
    container_name: app_springboot
    build: .
    ports:
      - "8080:8080"  # 映射 Spring Boot 应用的端口
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/juejin_clone?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - mysql  # 确保 mysql 容器在 spring 容器之前启动

  mysql:
    container_name: app_mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # 设置 MySQL 根密码
      MYSQL_DATABASE: juejin_clone  # 初始化数据库
    ports:
      - "3306:3306"  # 映射 MySQL 的端口
    volumes:
      - mysql_data:/var/lib/mysql  # 使用数据卷保存 MySQL 数据
    restart: always  # 确保容器崩溃时自动重启

volumes:
  mysql_data:  # MySQL 数据卷，用于持久化数据
